version: "3.9"
name: "technologie-internetowe-project"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: 
      context: ../backend
      dockerfile: ../backend/backend.Dockerfile
    container_name: node-backend
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
    depends_on:
      - mongo
    command: npm run dev

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  mongo-data: