version: "3.9"
name: "technologie-internetowe-project"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  backend:
    build: 
      context: ../backend
      dockerfile: ../backend/backend.Dockerfile
    container_name: node-backend
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
    depends_on:
      - mongo
    command: npm run dev
    networks:
      - backend

  # FRONTEEND DIRECTORY IS NEW APP WITH DEFAULT PAGES ROUTER. FRONTEND DIRECTORY IS AN NEXTJS WITH APP ROUTER THAT IS IN MY OPINION 'WEIRD' IN THE WAY HOW TO FETCH BACKEND DATA TO REACT CODE
  frontend:
    container_name: task-management-frontend
    build:
      context: ../fronteend/task-management-frontend/
      target: dev
      dockerfile: frontend.Dockerfile
    restart: always
    command: yarn dev
    environment:
      - NODE_ENV=${NODE_ENV}
      - WATCHPACK_POLLING=${WATCHPACK_POLLING}
    volumes:
      - ../fronteend/task-management-frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "80:3000"
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge